language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ecoeppasa-github"
    token:
      secure: "3734d03c8cb268e751779cea36dded423e6758b2"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
